OBJ = ./obj
BIN = ./bin
CXX = g++


all: ejercicio1 ejercicio2 ejercicio3 ejercicio4 ejercicio5 ejercicio6 ejercicio7 ejercicio9 ejercicio10

ejercicio1: $(OBJ)/ejercicio1.o
	${CXX} -o $(BIN)/ejercicio1 $(OBJ)/ejercicio1.o

$(OBJ)/ejercicio1.o: ejercicio1.cpp bintree.h node.hxx bintree.hxx
	${CXX} -c ejercicio1.cpp -o $(OBJ)/ejercicio1.o


ejercicio2: $(OBJ)/ejercicio2.o
	${CXX} -o $(BIN)/ejercicio2 $(OBJ)/ejercicio2.o

$(OBJ)/ejercicio2.o: ejercicio2.cpp bintree.h node.hxx bintree.hxx
	${CXX} -c ejercicio2.cpp -o $(OBJ)/ejercicio2.o


ejercicio3: $(OBJ)/ejercicio3.o
	${CXX} -o $(BIN)/ejercicio3 $(OBJ)/ejercicio3.o

$(OBJ)/ejercicio3.o: ejercicio3.cpp bintree.h node.hxx bintree.hxx
	${CXX} -c ejercicio3.cpp -o $(OBJ)/ejercicio3.o


ejercicio4: $(OBJ)/ejercicio4.o
	${CXX} -o $(BIN)/ejercicio4 $(OBJ)/ejercicio4.o

$(OBJ)/ejercicio4.o: ejercicio4.cpp bintree.h node.hxx bintree.hxx
	${CXX} -c ejercicio4.cpp -o $(OBJ)/ejercicio4.o


ejercicio5: $(OBJ)/ejercicio5.o
	${CXX} -o $(BIN)/ejercicio5 $(OBJ)/ejercicio5.o

$(OBJ)/ejercicio5.o: ejercicio5.cpp bintree.h node.hxx bintree.hxx
	${CXX} -c ejercicio5.cpp -o $(OBJ)/ejercicio5.o


ejercicio6: $(OBJ)/ejercicio6.o
	${CXX} -o $(BIN)/ejercicio6 $(OBJ)/ejercicio6.o

$(OBJ)/ejercicio6.o: ejercicio6.cpp bintree.h node.hxx bintree.hxx
	${CXX} -c ejercicio6.cpp -o $(OBJ)/ejercicio6.o


ejercicio7: $(OBJ)/ejercicio7.o
	${CXX} -o $(BIN)/ejercicio7 $(OBJ)/ejercicio7.o

$(OBJ)/ejercicio7.o: ejercicio7.cpp bintree.h node.hxx bintree.hxx
	${CXX} -c ejercicio7.cpp -o $(OBJ)/ejercicio7.o


ejercicio8: $(OBJ)/ejercicio8.o
	${CXX} -o $(BIN)/ejercicio8 $(OBJ)/ejercicio8.o

$(OBJ)/ejercicio8.o: ejercicio8.cpp bintree.h node.hxx bintree.hxx
	${CXX} -c ejercicio8.cpp -o $(OBJ)/ejercicio8.o


ejercicio9: $(OBJ)/ejercicio9.o
	${CXX} -o $(BIN)/ejercicio9 $(OBJ)/ejercicio9.o

$(OBJ)/ejercicio9.o: ejercicio9.cpp bintree.h node.hxx bintree.hxx
	${CXX} -c ejercicio9.cpp -o $(OBJ)/ejercicio9.o
	
ejercicio10: $(OBJ)/ejercicio10.o
	${CXX} -o $(BIN)/ejercicio10 $(OBJ)/ejercicio10.o

$(OBJ)/ejercicio10.o: ejercicio10.cpp bintree.h node.hxx bintree.hxx
	${CXX} -c ejercicio10.cpp -o $(OBJ)/ejercicio10.o




# ************ Limpieza  ************
clean :
	-rm -r $(OBJ)/* $(BIN)/* #$(ZIP)/*