all: ejercicio1 ejercicio2 ejercicio3 ejercicio4 ejercicio5  ejercicio7  ejercicio9 ejercicio10 ejercicio12 ejercicio13 ejercicio14

ejercicio1 : ejercicio1.cpp
	g++ -Wall -g -std=c++0x -o $@ $<

ejercicio2 : ejercicio2.cpp
	g++ -Wall -g -std=c++0x -o $@ $<

ejercicio3 : ejercicio3.cpp
	g++ -Wall -g -std=c++0x -o $@ $<

ejercicio4 : ejercicio4.cpp
	g++ -Wall -g -std=c++0x -o $@ $<

ejercicio5 : ejercicio5.cpp
	g++ -Wall -g -std=c++0x -o $@ $<

ejercicio7 : ejercicio7.cpp
	g++ -Wall -g -std=c++0x -o $@ $<

ejercicio9 : ejercicio9.cpp
	g++ -Wall -g -std=c++0x -o $@ $<

ejercicio10 : ejercicio10.cpp
	g++ -Wall -g -std=c++0x -o $@ $<

ejercicio12 : ejercicio12.cpp
	g++ -Wall -g -std=c++0x -o $@ $<

ejercicio13 : ejercicio13.cpp
	g++ -Wall -g -std=c++0x -o $@ $<

ejercicio14 : ejercicio14.cpp
	g++ -Wall -g -std=c++0x -o $@ $<


clean :
	-rm ejercicio? ejercicio??